language: python
python:
  - "3.6"
install:
  - python setup.py install
script:
  - python setup.py test
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev
  - pip install cython
  - pip install --only-binary=numpy,numba,pandas numpy numba pandas
